[theme]

base="light"
primaryColor="#00ABE1"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#00ABE1"
textColor="#161F6D"
font="sans serif"


[mapbox]

token = 'pk.eyJ1IjoicGFkb2ZyZW8iLCJhIjoiY2wwMGtjZTZ6MDlteDNicWdnZmUzMTN3ayJ9.qXpbfx5o9Gkzrz22cEUfnw'
