[theme]

#primaryColor = "#59ABE3"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor =  "#ebd2b9" # wheat  "#d7ab82" # yellow <-- not enough contrast
#textColor = "#6e7074" # grey
#font = "sans serif" # Font family (serif | sans serif | mono) for the page. Will not impact code areas.


primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"
